### PR TITLE
Move to Quarkus 1.11.0.Final

### PR DESCRIPTION
**Pull request by rsvoboda**
Move to Quarkus 1.11.0.Final - initial steps

https://github.com/quarkus-qe/quarkus-startstop/blob/master/testsuite/src/it/java/io/quarkus/ts/startstop/utils/CodeQuarkusExtensions.java needs update once the full platform gets released

### CODE REVIEW

**Review by jsmrcka — APPROVED** [review]

**Comment by rsvoboda** [comment]
CI is down / "broken", @Karm can you please look into it?

**Comment by Karm** [comment]
@rsvoboda Sure. Gimme a minute...

**Comment by Karm** [comment]
run tests

**Comment by rsvoboda** [comment]
Please switch to 1.11.0.Final + Graal 20.3.

Quarkus core is out, wole platform should be published tmr - https://github.com/quarkusio/quarkus/wiki/Release-Planning#1110final

**Comment by Karm** [comment]
run tests

**Comment by rsvoboda** [comment]
@Karm there is issue with centos8 machine

https://ci.modcluster.io/job/quarkus-startstop-github-pr/70/JAVA=HotSpot11,QUARKUS=1.11.0.Final,platform=karm-centos8-x86-64/console
```
ERROR: Step ‘Archive the artifacts’ aborted due to exception: 
java.nio.charset.MalformedInputException: Input length = 1
	at java.nio.charset.CoderResult.throwException(CoderResult.java:281)
	at java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:816)
	at org.apache.commons.compress.archivers.zip.NioZipEncoding.decode(NioZipEncoding.java:136)
	at org.apache.commons.compress.archivers.tar.TarUtils.parseName(TarUtils.java:299)
	at org.apache.commons.compress.archivers.tar.TarArchiveEntry.parseTarHeader(TarArchiveEntry.java:1299)
	at org.apache.commons.compress.archivers.tar.TarArchiveEntry.<init>(TarArchiveEntry.java:428)
	at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.getNextTarEntry(TarArchiveInputStream.java:314)
	at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.getNextEntry(TarArchiveInputStream.java:583)
	at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.getLongNameData(TarArchiveInputStream.java:393)
	at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.getNextTarEntry(TarArchiveInputStream.java:334)
	at hudson.FilePath.readFromTar(FilePath.java:2586)
Caused: java.io.IOException: Failed to extract /home/jenkins/jenkins/workspace/quarkus-startstop-github-pr/JAVA/HotSpot11/QUARKUS/1.11.0.Final/platform/karm-centos8-x86-64/transfer of 113 files
	at hudson.FilePath.readFromTar(FilePath.java:2612)
```

**Comment by Karm** [comment]
@rsvoboda I don't think there is.... see, it's the same on the Windows box too:

# Windows

```
[ERROR] Tests run: 27, Failures: 10, Errors: 1, Skipped: 3
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Quarkus StartStop TS: Parent 1.0.0-SNAPSHOT:
[INFO] 
[INFO] Quarkus StartStop TS: Parent ....................... SUCCESS [  0.309 s]
[INFO] testsuite .......................................... FAILURE [13:08 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  13:09 min
[INFO] Finished at: 2021-01-21T05:06:22-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project testsuite: There are test failures.
[ERROR] 
[ERROR] Please refer to C:\workspace\workspace\quarkus-start---e0eec712\JAVA\HotSpot11\QUARKUS\1.11.0.Final\platform\w2k19\testsuite\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :testsuite
Build step 'Conditional step (single)' marked build as failure
Archiving artifacts
ERROR: Step ‘Archive the artifacts’ aborted due to exception: 
java.nio.charset.MalformedInputException: Input length = 1
    at java.nio.charset.CoderResult.throwException(CoderResult.java:281)
    at java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:816)
    at org.apache.commons.compress.archivers.zip.NioZipEncoding.decode(NioZipEncoding.java:136)
    at org.apache.commons.compress.archivers.tar.TarUtils.parseName(TarUtils.java:299)
    at org.apache.commons.compress.archivers.tar.TarArchiveEntry.parseTarHeader(TarArchiveEntry.java:1299)
    at org.apache.commons.compress.archivers.tar.TarArchiveEntry.<init>(TarArchiveEntry.java:428)
    at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.getNextTarEntry(TarArchiveInputStream.java:314)
    at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.getNextEntry(TarArchiveInputStream.java:583)
    at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.getLongNameData(TarArchiveInputStream.java:393)
    at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.getNextTarEntry(TarArchiveInputStream.java:334)
    at hudson.FilePath.readFromTar(FilePath.java:2586)
Caused: java.io.IOException: Failed to extract C:\workspace\workspace\quarkus-start---e0eec712\JAVA\HotSpot11\QUARKUS\1.11.0.Final\platform\w2k19/transfer of 79 files
    at hudson.FilePath.readFromTar(FilePath.java:2612)
    at hudson.FilePath.copyRecursiveTo(FilePath.java:2390)
    at jenkins.model.StandardArtifactManager.archive(StandardArtifactManager.java:70)
    at hudson.tasks.ArtifactArchiver.perform(ArtifactArchiver.java:252)
    at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:741)
    at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
    at hudson.model.Build$BuildExecution.post2(Build.java:186)
    at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
    at hudson.model.Run.execute(Run.java:1905)
    at hudson.matrix.MatrixRun.run(MatrixRun.java:153)
    at hudson.model.ResourceController.execute(ResourceController.java:97)
    at hudson.model.Executor.run(Executor.java:428)
Recording test results
[Checks API] No suitable checks publisher found.
[WS-CLEANUP] Deleting project workspace...
[WS-CLEANUP] Deferred wipeout is used...
[WS-CLEANUP] done
Finished: FAILURE
```

# Linux

```
[INFO] Tests run: 34, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ testsuite ---
[INFO] Building jar: /home/jenkins/jenkins/workspace/quarkus-startstop-github-pr/JAVA/HotSpot11/QUARKUS/1.11.0.Final/platform/karm-centos8-x86-64/testsuite/target/testsuite-1.0.0-SNAPSHOT.jar
[INFO] 
[INFO] --- maven-failsafe-plugin:2.22.2:integration-test (default) @ testsuite ---
[INFO] 
[INFO] --- maven-failsafe-plugin:2.22.2:verify (default) @ testsuite ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Quarkus StartStop TS: Parent 1.0.0-SNAPSHOT:
[INFO] 
[INFO] Quarkus StartStop TS: Parent ....................... SUCCESS [  0.130 s]
[INFO] testsuite .......................................... SUCCESS [18:41 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  18:41 min
[INFO] Finished at: 2021-01-21T11:11:54+01:00
[INFO] ------------------------------------------------------------------------
Regular expression run condition: Expression=[.*w.*], Label=[karm-centos8-x86-64]
Run condition [Regular expression match] preventing perform for step [Execute Windows batch command]
Archiving artifacts
ERROR: Step ‘Archive the artifacts’ aborted due to exception: 
java.nio.charset.MalformedInputException: Input length = 1
    at java.nio.charset.CoderResult.throwException(CoderResult.java:281)
    at java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:816)
    at org.apache.commons.compress.archivers.zip.NioZipEncoding.decode(NioZipEncoding.java:136)
    at org.apache.commons.compress.archivers.tar.TarUtils.parseName(TarUtils.java:299)
    at org.apache.commons.compress.archivers.tar.TarArchiveEntry.parseTarHeader(TarArchiveEntry.java:1299)
    at org.apache.commons.compress.archivers.tar.TarArchiveEntry.<init>(TarArchiveEntry.java:428)
    at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.getNextTarEntry(TarArchiveInputStream.java:314)
    at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.getNextEntry(TarArchiveInputStream.java:583)
    at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.getLongNameData(TarArchiveInputStream.java:393)
    at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.getNextTarEntry(TarArchiveInputStream.java:334)
    at hudson.FilePath.readFromTar(FilePath.java:2586)
Caused: java.io.IOException: Failed to extract /home/jenkins/jenkins/workspace/quarkus-startstop-github-pr/JAVA/HotSpot11/QUARKUS/1.11.0.Final/platform/karm-centos8-x86-64/transfer of 113 files
    at hudson.FilePath.readFromTar(FilePath.java:2612)
    at hudson.FilePath.copyRecursiveTo(FilePath.java:2390)
    at jenkins.model.StandardArtifactManager.archive(StandardArtifactManager.java:70)
    at hudson.tasks.ArtifactArchiver.perform(ArtifactArchiver.java:252)
    at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:741)
    at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
    at hudson.model.Build$BuildExecution.post2(Build.java:186)
    at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
    at hudson.model.Run.execute(Run.java:1905)
    at hudson.matrix.MatrixRun.run(MatrixRun.java:153)
    at hudson.model.ResourceController.execute(ResourceController.java:97)
    at hudson.model.Executor.run(Executor.java:428)
Recording test results
[Checks API] No suitable checks publisher found.
[WS-CLEANUP] Deleting project workspace...
[WS-CLEANUP] Deferred wipeout is used...
[WS-CLEANUP] done
Finished: FAILURE
```


What changed: The only thing on the infrastructure side was update of JDKs to the latest January 19th CPU.

**Comment by Karm** [comment]
@rsvoboda if you have any suggestions about 
```
ERROR: Step ‘Archive the artifacts’ aborted due to exception: 
java.nio.charset.MalformedInputException: Input length = 1
```

I am happy to implement them on the infra side....

**Comment by rsvoboda** [comment]
Did you reconnect the slaves? I don't what else could be making such troubles.

**Comment by Karm** [comment]
@rsvoboda  Windows executors were restarted....

**Comment by Karm** [comment]
@rsvoboda Other jobs are fine...  e.g.
```
23:21:05 Recording test results
23:21:06 [Checks API] No suitable checks publisher found.
23:21:06 Archiving artifacts
23:21:06 Email was triggered for: Failure - Any
23:21:06 Sending email for trigger: Failure - Any
23:21:06 Sending email to: karm@redhat.com
23:21:07 [WS-CLEANUP] Deleting project workspace...
23:21:07 [WS-CLEANUP] Deferred wipeout is used...
23:21:07 [WS-CLEANUP] done
```

Hmmm.

**Comment by Karm** [comment]
run tests

**Comment by rsvoboda** [comment]
Centos run passed, failure in post build step.
Windows is not yet supported platform, failures are noted, need to be investigated as followup action.
@mjurc pls review (and merge when ok)

**Review by mjurc — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
