### PR TITLE
Updated README.md and details about tests

### PR DESCRIPTION
**Pull request by rsvoboda**
- Details about tests
 - Updated README.md

### CODE REVIEW

**Comment by rsvoboda** [comment]
run tests

**Comment by rsvoboda** [comment]
@mjurc can you please look at this? It waits for your approval and merge ;)

**Comment by Karm** [comment]
@rsvoboda CI passed in Windows, it is pending on Centos, because I have the box offline. Will return it to Jenkins a couple of hours max.

**Comment by mjurc** [comment]
:+1:

**Pull request merged**
