### PR TITLE
Fix JVM build, dedicated job for format validation

### PR DESCRIPTION
**Pull request by rsvoboda**
Fix JVM build, dedicated job for format validation

Before this fix the JVM run was not doing a lot, just checking the root pom.xml

### CODE REVIEW

**Review by Sgitario — COMMENTED** [review]
I see the issue, but why adding a new job just to validate the sources? :/ 
As far I see, just adding `-Pide -Dvalidate-format` fixes the issue.

**Comment by rsvoboda** [comment]
Fast fail in case of invalid formatting

**Comment by rsvoboda** [comment]
code.quarkus job fail is expected as code.quarkus is on 2.0.2.Final and we need to adjust the TS for that version (in progress)

**Comment by Sgitario** [comment]
> code.quarkus job fail is expected as code.quarkus is on 2.0.2.Final and we need to adjust the TS for that version (in progress)

Ok, merging

**Pull request merged**
