### PR TITLE
Update Quarkus version to 3.9 and update reactive artifacts

### PR DESCRIPTION
**Pull request by jedla97**
As [code.quarkus.io](code.quarkus.io) now have default 3.9 it failing to find some artifacts which were renamed. 
The replacement guide was https://github.com/quarkusio/quarkus/blob/main/relocations/generaterelocations.java

Also there was change that when generating codestarts `index.html` is no longer generated https://github.com/quarkusio/quarkus/pull/37680
We testing if it's awailable but to me it's seems just to check if Quarkus start and is able to receive requests

### CODE REVIEW

**Comment by rsvoboda** [comment]
3.9.2 is out, @jedla97 can you update this PR?

**Comment by rsvoboda** [comment]
```
[INFO] --- quarkus-maven-plugin:3.9.1:create (default-cli) @ standalone-pom ---
[WARNING] The extension catalog will be narrowed to the io.quarkus.platform:quarkus-bom:3.9.1 platform release. To enable the complete Quarkiverse extension catalog along with the latest recommended platform releases, please, make sure the extension registry client is enabled.
[ERROR] Cannot find a dependency matching 'quarkus-jaxrs-client', maybe a typo?
```

**Comment by fedinskiy** [comment]
@rsvoboda could you take a look at this PR? CI is green and these changes are required for https://github.com/quarkus-qe/quarkus-startstop/pull/355

**Comment by fedinskiy** [comment]
Thank you for the fix!

**Pull request merged**
