### PR TITLE
[RUN CI] Create Quarkus 3.2 verison with OTel

### PR DESCRIPTION
**Pull request by michalvavrik**
here to run CI

### CODE REVIEW

**Comment by rsvoboda** [comment]
Hi @michalvavrik, it's better to run on your machine, GH actions are VMs without strong perf guarantees, that's why the threshold are quite big

Main can't be used because of rename, but you can still use 3.8 to do the comparison on the same app

This is my quick local experiment
```
git clone https://github.com/quarkus-qe/quarkus-startstop -b 3.8
cd quarkus-startstop
sdk use java 21.0.2-graalce
sdk use maven 3.8.8

mvn clean verify -pl testsuite -Dtest=StartStopTest#fullMicroProfileNative -Dquarkus.version=3.8.5 -Dstart-stop.iterations=25
mvn clean verify -pl testsuite -Dtest=StartStopTest#fullMicroProfileNative -Dquarkus.version=3.2.12.Final -Dstart-stop.iterations=25
```

Look into `AVG timeToFirstOKRequest ...` and `AVG rssKb ...` in the log

I did one quick and dirty change
```diff
diff --git a/testsuite/src/it/java/io/quarkus/ts/startstop/StartStopTest.java b/testsuite/src/it/java/io/quarkus/ts/startstop/StartStopTest.java
index f1b92e5..fe269e0 100644
--- a/testsuite/src/it/java/io/quarkus/ts/startstop/StartStopTest.java
+++ b/testsuite/src/it/java/io/quarkus/ts/startstop/StartStopTest.java
@@ -100,7 +100,7 @@ public class StartStopTest {
             long buildEnds = System.currentTimeMillis();

             assertTrue(buildLogA.exists());
-            checkLog(cn, mn, app, mvnCmds, buildLogA);
+//            checkLog(cn, mn, app, mvnCmds, buildLogA);

             if (mvnCmds == MvnCmds.NATIVE) {
                 String nativeBinaryLocation = mvnCmds.mvnCmds[1][0];
```
otherwise 3.2 run fails on these complains:
```
[ERROR] Failures:
[ERROR]   StartStopTest.fullMicroProfileNative:220->testRuntime:103 NATIVE log should not contain error or warning lines that are not whitelisted. See testsuite/target/archived-logs/io.quarkus.ts.startstop.StartStopTest/fullMicroProfileNative/native-build.log and check these offending lines:
java.lang.IllegalAccessError: class io.quarkus.runner.Feature (in unnamed module @0x51288417) cannot access class org.graalvm.nativeimage.impl.RuntimeClassInitializationSupport (in module org.graalvm.nativeimage) because module org.graalvm.nativeimage does not export org.graalvm.nativeimage.impl to unnamed module @0x51288417
WARNING: Unknown module: org.graalvm.sdk specified to --add-exports
Warning: The option '-H:+AllowFoldMethods' is experimental and must be enabled via '-H:+UnlockExperimentalVMOptions' in the future.
Warning: The option '-H:-UseServiceLoaderFeature' is experimental and must be enabled via '-H:+UnlockExperimentalVMOptions' in the future.
Warning: The option '-H:BuildOutputJSONFile=quarkus-runner-build-output-stats.json' is experimental and must be enabled via '-H:+UnlockExperimentalVMOptions' in the future. ==> expected: <true> but was: <false>
```

**Comment by michalvavrik** [comment]
> Hi @michalvavrik, it's better to run on your machine, GH actions are VMs without strong perf guarantees, that's why the threshold are quite big

I do other things on my workstation and this CI is very quick - so I use it for adjustments, not for getting numbers. For example, it also runs when I turn of my overworked laptop. I thought I'll use perflab job for actual numbers, but I'll try your experiment steps as well.

**Comment by michalvavrik** [comment]
> otherwise 3.2 run fails on these complains:

I expect it fails because you use JDK 21, just use 17 and it will work.

**Comment by rsvoboda** [comment]
Can be this closed @michalvavrik ?

**Comment by michalvavrik** [comment]
> Can be this closed @michalvavrik ?

I wonder what should be done for 3.2 branch in regards of https://github.com/quarkus-qe/quarkus-startstop/pull/379. If eng team doesn't need 3.2 base anymore, it would make me happy. I'll have to ask.

**Comment by michalvavrik** [comment]
yeah, let's close it, I don't want to work on this unless required.

**Comment by michalvavrik** [comment]
on second thought, I think I simply have to prepare 3.2 base line :/ so I'll keep using this PR for testing.

**Comment by michalvavrik** [comment]
I'll keep it open for few days and unless I hear feedback from eng team, I'll close this as they don't need PR per say. (just they can see how to setup env)

**Pull request closed without merging**
