### PR TITLE
Move Java baseline to 17

### PR DESCRIPTION
**Pull request by michalvavrik**
Quarkus changed, we need to get Quarkus Startstop ready for 3.7. See also https://github.com/quarkus-qe/quarkus-test-suite/pull/1556.

### CODE REVIEW

**Comment by jedla97** [comment]
FYI Run daily CI and it's green https://github.com/quarkus-qe/quarkus-startstop/actions/runs/7088432644

**Comment by michalvavrik** [comment]
> FYI Run daily CI and it's green https://github.com/quarkus-qe/quarkus-startstop/actions/runs/7088432644

https://github.com/quarkus-qe/quarkus-startstop/actions/runs/7088432644/job/19290919431 is not targeting Quarkus 999-SNAPSHOT.

**Comment by michalvavrik** [comment]
I think I get it @jedla97 you tried to say that #327 fixed qute failures, ok, thank you

**Comment by michalvavrik** [comment]
> https://github.com/quarkus-qe/quarkus-startstop/blob/main/testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusSiteTest.java#L111 .. add case for Java 21, I would also remove Java 11 check as it will go away soon
> 
> https://github.com/quarkus-qe/quarkus-startstop/blob/main/testsuite/src/it/java/io/quarkus/ts/startstop/CodeQuarkusTest.java#L222 ... change it to `java21BasedProject`

done, thanks

**Comment by michalvavrik** [comment]
CodeQuarkusSiteTest tests https://code.quarkus.redhat.com/, hence it only detects 11 and 17.

**Comment by rsvoboda** [comment]
> CodeQuarkusSiteTest tests https://code.quarkus.redhat.com/, hence it only detects 11 and 17.

That's true in branches, but not in main - see https://github.com/quarkus-qe/quarkus-startstop/blob/main/testsuite/src/it/java/io/quarkus/ts/startstop/utils/Commands.java#L186

**Comment by rsvoboda** [comment]
aha, site check, you are correct, my bad.

**Comment by michalvavrik** [comment]
> FYI Run daily CI and it's green https://github.com/quarkus-qe/quarkus-startstop/actions/runs/7088432644

I adjusted PR description. It can take me while, but I will figure every hint eventually!

**Comment by michalvavrik** [comment]
> Error:    ArtifactGeneratorTest.manyReactiveExtensionsSetA:412->testRuntime:361 GENERATOR log should not contain error or warning lines that are not whitelisted. See testsuite\target\archived-logs\io.quarkus.ts.startstop.ArtifactGeneratorTest\manyReactiveExtensionsSetA\dev-run.log and check these offending lines: 
2023-12-04 19:53:34,749 WARN  [io.qua.dep.dev.JavaCompilationProvider] (vert.x-worker-thread-1) Annotation processing is enabled because one or more processors were found

Opened issue https://github.com/quarkusio/quarkus/issues/37532

**Review by jedla97 — APPROVED** [review]
Thanks for resolving errors. LGTM! I look and didn't find any other occurrences of java 11 except site which were previously discussed.

**Pull request merged**
