### PR TITLE
Rename quarkus-rest(easy) dependencies

### PR DESCRIPTION
**Pull request by mocenas**
Rename dependencies as was done in https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.9

### CODE REVIEW

**Review by jedla97 — APPROVED** [review]

**Comment by jedla97** [comment]
LGTM! Waiting for CI

**Comment by rsvoboda** [comment]
sorry, the change should went to main, that's why I created 3.15 today, so this PR doesn't affect RHBQ 3.15 runs. I want to keep easy way to run the same StartStopTests with 3.8 and 3.15.

**Comment by rsvoboda** [comment]
https://github.com/quarkus-qe/quarkus-startstop/pull/397 was created

**Comment by rsvoboda** [comment]
@mocenas please prepare this change for `main`

**Comment by mocenas** [comment]
> @mocenas please prepare this change for `main`

Changes for main prepared - https://github.com/quarkus-qe/quarkus-startstop/pull/398

**Pull request merged**
