### PR TITLE
Append properties starting with quarkus.native to the native image build command

### PR DESCRIPTION
**Pull request by rsvoboda**
Append properties starting with `quarkus.native` to the native image build command

For details see addition to README.md in this PR

### CODE REVIEW

**Comment by rsvoboda** [comment]
centos8 run finished successfully, just the post build action failed with `Caused: java.io.IOException: Failed to extract /home/jenkins/jenkins/workspace/quarkus-startstop-github-pr/JAVA/HotSpot11/QUARKUS/1.3.2.Final/platform/karm-centos8-x86-64/transfer of 109 files`

windows run failed in one test case - https://ci.modcluster.io/job/quarkus-startstop-github-pr/41/JAVA=HotSpot11,QUARKUS=1.3.2.Final,platform=w2k19/testReport/io.quarkus.ts.startstop/SpecialCharsTest/diacriticsDEV_TestInfo_/
Not related to this PR, I will look into it if it's CI machine or general Windows issues and create new PR if needed. This PR shouldn't be blocked by it

**Comment by rsvoboda** [comment]
I executed SpecialCharsTest on my home Windows 10 machine and it passed without problem.
So there is issue on the CI Windows machine, probably it needs support for Czech language installed

**Comment by Karm** [comment]
@rsvoboda Czech is indeed not installed.  Should I add it?

**Comment by rsvoboda** [comment]
@Karm please install it and please take a look at centos8 node, `Archive the artifacts` fails there weirdly.

**Comment by Karm** [comment]
@rsvoboda I installed Czech a Japanese support on the Windows 2019 box.

**Comment by Karm** [comment]
@rsvoboda Dunno about centos8, there was a weird directory in the said path in the workspace. I deleted it... We shall see.

**Comment by rsvoboda** [comment]
Good, we will see with the next PR.

**Pull request merged**
