### PR TITLE
Fixes for issues reported by Coverity

### PR DESCRIPTION
**Pull request by rsvoboda**
- Make header strings in LogBuilder static
- Ensure UTF-8 usage instead of platform default charset

### CODE REVIEW

**Comment by rsvoboda** [comment]
Looks like I have hit native limitation

https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/VarHandleFeature.java#L199

**Comment by rsvoboda** [comment]
I played a bit locally but I couldn't see this warning on GraalVM 19.3.1.r11.

I see this warning on GraalVM 20.1.0.r11.

I tried master of this TS on GraalVM 20.1.0.r11 and I can see:
WARNING GR-10238: VarHandle for static field is currently not fully supported. Static field private static volatile java.lang.System$Logger jdk.internal.event.EventHelper.securityLogger is not properly marked for Unsafe access!

**Comment by Karm** [comment]
@rsvoboda I am sorry, I missed the message.

```
(03:08:57 PM) rsvoboda: ping … any tips what is causing https://ci.modcluster.io/job/quarkus-startstop-github-pr/35/JAVA=HotSpot11,QUARKUS=1.3.2.Final,platform=karm-centos8-x86-64/testReport/junit/io.quarkus.ts.startstop/StartStopTest/jaxRsMinimalNative_TestInfo_/ ?
(03:48:50 PM) rsvoboda: I don't see what version of GraalVM is used
```

I updated Graal Java 11 to default to 20.1 on Centos slaves without telling anyone. Pretty bad move I admit.

```

$ ls -lah
 .
 ..
 graalvm-ce-java11 -> /usr/java/graalvm-ce-java11-20.1.0
 graalvm-ce-java11-19 -> /usr/java/graalvm-ce-java11-19.3.1
 graalvm-ce-java11-19.3.1
 graalvm-ce-java11-20.0.0
 graalvm-ce-java11-20.1.0
 graalvm-ce-java8 -> /usr/java/graalvm-ce-java8-20.0.0
 graalvm-ce-java8-19 -> /usr/java/graalvm-ce-java8-19.3.1
 graalvm-ce-java8-19.3.1
 graalvm-ce-java8-20.0.0
 jdk-11.0.6+10-hotspot
 jdk-11.0.6+10-j9
 jdk8u242-b08-hotspot
 jdk8u242-b08-j9
 openjdk-11.0.8+4
 OpenJDK11U-jdk_x64_linux_11.0.8_4_ea.tar.gz
 OpenJDK11U-static-libs_x64_linux_11.0.8_4_ea.tar.gz
```

"19" is  graalvm-ce-java11-19 now.

I am sorry if it caused trouble...

**Comment by rsvoboda** [comment]
@Karm no problem, we would hit GR-10238 sooner or later

**Pull request merged**
