### PR TITLE
[3.8] Change name of a copied artifact

### PR DESCRIPTION
**Pull request by fedinskiy**
See https://github.com/quarkusio/quarkus/issues/39368 for explanation why the old way stopped to work

### CODE REVIEW

**Comment by fedinskiy** [comment]
I expect for CI to fail on ArtifactGeneratorTest[1] due to relocation warnings , but it should be the only failure.

[1] https://github.com/quarkus-qe/quarkus-startstop/pull/345#issuecomment-1991693426

**Review by rsvoboda — CHANGES_REQUESTED** [review]
But we will have those relocations for the whole time of 3.8, won't we?

Personally I would add `relocated to io.quarkus:quarkus-resteasy-client-jackson` to the witelist - add new commit to this PR so the changes are decoupled.

So the https://github.com/quarkusio/quarkus/issues/39368 issue can be closed?

**Comment by fedinskiy** [comment]
@rsvoboda 
> but we will have those relocations for the whole time of 3.8

Luckily no, the fix https://github.com/quarkusio/quarkus/issues/39330 is expected in 3.8.3.

> So the https://github.com/quarkusio/quarkus/issues/39368 issue can be closed?

I found a workaround, but maybe upstream folks will fix the original issue, so I suggest to leave it as is.

**Comment by rsvoboda** [comment]
ok, I think 3.8.3 is planned this week, I will merge it

**Pull request merged**
